### ISSUE TITLE
User is able to open a file that doesn't exist

### ISSUE THREAD

**Issue by LloydBG** [sebbrudzinski/Open-LaTeX-Studio#36]
Description:
User is able to open a file that doesn't exist.

Steps to Recreate:
1. Open Open-LaTex-Studio
2. Navigate to File>Open File
3. Open a file that doesn't exist

Expected Result:
A pop up warning to tell the user that the specified file doesn't exist and returns the user to the Open file window

Actual Result:
The user is able to open a file that doesn't exist. 

Affected Environment:
Windows 7
Linux - Ubuntu 14.04.2

Screenshots:
Update File is the only .tex file in this folder and Test File is being opened even though it doesn't exist
![image](https://cloud.githubusercontent.com/assets/13062974/8546091/4b6edf3c-24e7-11e5-9f2e-7d92cffcc6d0.png)
FileNotFoundException
![image](https://cloud.githubusercontent.com/assets/13062974/8546110/7e633f8c-24e7-11e5-8ccf-d0432803851b.png)
After Clicking the cancel button from the FileNotFoundException, the non-existing file is opened and ready to use
![image](https://cloud.githubusercontent.com/assets/13062974/8546147/bf3e2e7c-24e7-11e5-97a0-42a8f642ec2c.png)

**Comment by Labelpm** [comment]
Hi ebbrudzinski I've fixed this issue, please take a look at repository.

**Comment by sebbrudzinski** [comment]
Hi! Could you please create a pull request from your repository? We will then take a look at this and merge if it indeed resolves the issue. Cheers :)

**Comment by Labelpm** [comment]
Hi Sebastian,  Done.  Thank, 09.07.2015, 11:00, "Sebastian Brudziński" <notifications@github.com>:Hi! Could you please create a pull request from your repository? We will then take a look at this and merge if it indeed resolves the issue. Cheers :)—Reply to this email directly or view it on GitHub.

**Comment by LloydBG** [comment]
RETEST FAILED

The issue is still occurring for both Windows 7 and Linux - Ubuntu 14.04.2. This was retested using the latest code changes.

Windows 7
![image](https://cloud.githubusercontent.com/assets/13062974/8613569/01f84536-2713-11e5-8671-e4709f97fce5.png)

Linux - Ubuntu 14.04.2
![image](https://cloud.githubusercontent.com/assets/13062974/8613607/81e863c0-2713-11e5-928f-c08642cfb010.png)

**Comment by sebbrudzinski** [comment]
Did you download the pull request? The change is not yet in the Open LaTeX Studio codebase

**Comment by LloydBG** [comment]
@sebbrudzinski I'm sorry but how can I download the pull request?

**Comment by LloydBG** [comment]
RETEST PASSED

Description:
When the user try to open a file which doesn't exist the user is automatically redirected to the home screen after clicking "open" button.

Issue:
@sebbrudzinski 
My concern is can we add a pop up warning to a user when he is trying to open a file which doesn't exist and after he confirms the warning he will be redirected back to the Open file window?

**Comment by Labelpm** [comment]
@LloydBG Please pull it's again.

"and after he confirms the warning he will be redirected back to the Open file window?"
About this one, my suggestion is allow only a dialog box and leave user on home page,  it's a common practice

**Comment by LloydBG** [comment]
@Labelpm yeah a dialog box will do. I guess redirecting the user to the home page will also be good, I just found a software that redirects the user to the open file window that's why I suggest it :)

**Comment by sebbrudzinski** [comment]
Fixed by @Labelpm Thanks! :)
